#!/bin/bash

# Kernel Debloat Script for SM6150 (surya_defconfig)
# This script removes unnecessary features to reduce kernel size while maintaining stability

echo "Starting kernel debloat for SM6150..."

# Backup original defconfig
cp arch/arm64/configs/surya_defconfig arch/arm64/configs/surya_defconfig.backup

# Function to disable config options
disable_config() {
    sed -i "s/CONFIG_$1=y/# CONFIG_$1 is not set/g" arch/arm64/configs/surya_defconfig
    sed -i "s/CONFIG_$1=m/# CONFIG_$1 is not set/g" arch/arm64/configs/surya_defconfig
}

# Function to comment out config lines
comment_config() {
    sed -i "s/^CONFIG_$1/# CONFIG_$1/g" arch/arm64/configs/surya_defconfig
}

echo "Removing unnecessary input drivers..."

# Disable unused input drivers (keep only essential ones)
disable_config "INPUT_JOYSTICK"
disable_config "JOYSTICK_XPAD"
disable_config "JOYSTICK_PSXPAD_SPI"
disable_config "INPUT_TABLET"

# Disable unused touchscreen drivers (keep only essential)
disable_config "TOUCHSCREEN_ADS7846"
disable_config "TOUCHSCREEN_AD7877"
disable_config "TOUCHSCREEN_AD7879"
disable_config "TOUCHSCREEN_AR1021_I2C"
disable_config "TOUCHSCREEN_ATMEL_MXT"
disable_config "TOUCHSCREEN_AUO_PIXCIR"
disable_config "TOUCHSCREEN_BU21013"
disable_config "TOUCHSCREEN_CHIPONE_ICN8318"
disable_config "TOUCHSCREEN_CY8CTMG110"
disable_config "TOUCHSCREEN_CYTTSP_CORE"
disable_config "TOUCHSCREEN_CYTTSP4_CORE"
disable_config "TOUCHSCREEN_DYNAPRO"
disable_config "TOUCHSCREEN_EDT_FT5X06"
disable_config "TOUCHSCREEN_EETI"
disable_config "TOUCHSCREEN_EGALAX_SERIAL"
disable_config "TOUCHSCREEN_EXC3000"
disable_config "TOUCHSCREEN_FUJITSU"
disable_config "TOUCHSCREEN_GOODIX"
disable_config "TOUCHSCREEN_HIDEEP"
disable_config "TOUCHSCREEN_ILI210X"
disable_config "TOUCHSCREEN_ILITEK"
disable_config "TOUCHSCREEN_S6SY761"
disable_config "TOUCHSCREEN_GUNZE"
disable_config "TOUCHSCREEN_EKTF2127"
disable_config "TOUCHSCREEN_ELAN"
disable_config "TOUCHSCREEN_ELO"
disable_config "TOUCHSCREEN_WACOM_W8001"
disable_config "TOUCHSCREEN_WACOM_I2C"
disable_config "TOUCHSCREEN_MAX11801"
disable_config "TOUCHSCREEN_MCS5000"
disable_config "TOUCHSCREEN_MMS114"
disable_config "TOUCHSCREEN_MELFAS_MIP4"
disable_config "TOUCHSCREEN_MTOUCH"
disable_config "TOUCHSCREEN_INEXIO"
disable_config "TOUCHSCREEN_MK712"
disable_config "TOUCHSCREEN_PENMOUNT"
disable_config "TOUCHSCREEN_EDT_FT5X06"
disable_config "TOUCHSCREEN_TOUCHRIGHT"
disable_config "TOUCHSCREEN_TOUCHWIN"
disable_config "TOUCHSCREEN_TI_AM335X_TSC"
disable_config "TOUCHSCREEN_UCB1400"
disable_config "TOUCHSCREEN_PIXCIR"
disable_config "TOUCHSCREEN_WDT87XX_I2C"
disable_config "TOUCHSCREEN_WM831X"
disable_config "TOUCHSCREEN_WM97XX"
disable_config "TOUCHSCREEN_USB_COMPOSITE"
disable_config "TOUCHSCREEN_MC13783"
disable_config "TOUCHSCREEN_TOUCHIT213"
disable_config "TOUCHSCREEN_TSC_SERIO"
disable_config "TOUCHSCREEN_TSC200X_CORE"
disable_config "TOUCHSCREEN_TSC2004"
disable_config "TOUCHSCREEN_TSC2005"
disable_config "TOUCHSCREEN_TSC2007"
disable_config "TOUCHSCREEN_RM_TS"
disable_config "TOUCHSCREEN_SILEAD"
disable_config "TOUCHSCREEN_SIS_I2C"
disable_config "TOUCHSCREEN_ST1232"
disable_config "TOUCHSCREEN_STMFTS"
disable_config "TOUCHSCREEN_SURFACE3_SPI"
disable_config "TOUCHSCREEN_SX8654"
disable_config "TOUCHSCREEN_TPS6507X"
disable_config "TOUCHSCREEN_ZET6223"
disable_config "TOUCHSCREEN_ZFORCE"
disable_config "TOUCHSCREEN_COLIBRI_VF50"
disable_config "TOUCHSCREEN_ROHM_BU21023"

echo "Removing unnecessary charger drivers..."

# Disable unused charger drivers (keep only QCOM SMB5)
disable_config "CHARGER_SBS"
disable_config "CHARGER_ISP1704"
disable_config "CHARGER_MAX8903"
disable_config "CHARGER_LP8727"
disable_config "CHARGER_GPIO"
disable_config "CHARGER_MANAGER"
disable_config "CHARGER_LTC3651"
disable_config "CHARGER_DETECTOR_MAX14656"
disable_config "CHARGER_QCOM_SMBB"
disable_config "CHARGER_BQ2415X"
disable_config "CHARGER_BQ24190"
disable_config "CHARGER_BQ24257"
disable_config "CHARGER_BQ24735"
disable_config "CHARGER_BQ25890"
disable_config "CHARGER_SMB347"
disable_config "CHARGER_RT9455"

# Disable unused QCOM charger variants
disable_config "SMB1351_USB_CHARGER"
disable_config "SMB1355_SLAVE_CHARGER"
disable_config "SMB138X_CHARGER"
disable_config "SMB1390_CHARGE_PUMP"
disable_config "SMB1390_CHARGE_PUMP_PSY"
disable_config "SMB1398_CHARGER"
disable_config "SMB358_CHARGER"
disable_config "QPNP_SMB2"
disable_config "QPNP_QNOVO"
disable_config "QPNP_QNOVO5"

echo "Removing unnecessary networking features..."

# Disable unused network protocols
disable_config "NET_IPIP"
disable_config "NET_IPGRE"
disable_config "NET_IPGRE_DEMUX"
disable_config "NET_IPVTI"
disable_config "NET_UDP_TUNNEL"
disable_config "NET_FOU"
disable_config "NET_FOU_IP_TUNNELS"
disable_config "IP_MROUTE"
disable_config "SYN_COOKIES"
disable_config "NET_IPGRE"
disable_config "IPV6_SIT"
disable_config "IPV6_GRE"
disable_config "IPV6_FOU"
disable_config "IPV6_FOU_TUNNEL"
disable_config "IPV6_MULTIPLE_TABLES"
disable_config "IPV6_SUBTREES"
disable_config "IPV6_MROUTE"
disable_config "IPV6_SEG6_LWTUNNEL"
disable_config "IPV6_SEG6_HMAC"
disable_config "NETFILTER_NETLINK_LOG"
disable_config "NF_CT_NETLINK"
disable_config "NF_CT_NETLINK_TIMEOUT"
disable_config "NF_TABLES"
disable_config "NETFILTER_XT_TARGET_LOG"
disable_config "NETFILTER_XT_TARGET_NFLOG"
disable_config "NETFILTER_XT_TARGET_RATEEST"
disable_config "NETFILTER_XT_TARGET_LED"
disable_config "NETFILTER_XT_TARGET_HMARK"

echo "Removing unnecessary filesystem support..."

# Disable unused filesystems (keep only essential)
disable_config "EXT2_FS"
disable_config "EXT3_FS"
disable_config "EXT4_FS"
disable_config "REISERFS_FS"
disable_config "JFS_FS"
disable_config "XFS_FS"
disable_config "GFS2_FS"
disable_config "OCFS2_FS"
disable_config "BTRFS_FS"
disable_config "NILFS2_FS"
disable_config "F2FS_FS"
disable_config "ZONEFS_FS"
disable_config "BFQ_GROUP_IOSCHED"
disable_config "KYBER_IOSCHED"
disable_config "BFQ_GROUP_IOSCHED"

echo "Removing debug and development features..."

# Disable debug features
disable_config "DEBUG_INFO"
disable_config "DEBUG_INFO_REDUCED"
disable_config "DEBUG_INFO_SPLIT"
disable_config "DEBUG_INFO_DWARF4"
disable_config "GDB_SCRIPTS"
disable_config "DEBUG_KERNEL"
disable_config "DEBUG_MISC"
disable_config "DEBUG_BUGVERBOSE"
disable_config "DEBUG_LIST"
disable_config "DEBUG_SG"
disable_config "DEBUG_NOTIFIERS"
disable_config "DEBUG_CREDENTIALS"
disable_config "RCU_TRACE"
disable_config "DEBUG_BLK_CGROUP"
disable_config "DEBUG_FORCE_WEAK_PER_CPU"
disable_config "FAULT_INJECTION"
disable_config "FAILSLAB"
disable_config "FAIL_PAGE_ALLOC"
disable_config "FAIL_MAKE_REQUEST"
disable_config "FAIL_IO_TIMEOUT"
disable_config "FAIL_FUTEX"
disable_config "FAULT_INJECTION_DEBUG_FS"
disable_config "FAULT_INJECTION_STACKTRACE_FILTER"
disable_config "LATENCYTOP"
disable_config "SCHED_DEBUG"
disable_config "SCHEDSTATS"
disable_config "DEBUG_PREEMPT"

echo "Removing unused crypto algorithms..."

# Disable unused crypto (keep only essential)
disable_config "CRYPTO_ANSI_CPRNG"
disable_config "CRYPTO_DRBG_MENU"
disable_config "CRYPTO_DRBG_HMAC"
disable_config "CRYPTO_DRBG_HASH"
disable_config "CRYPTO_RNG_DEFAULT"
disable_config "CRYPTO_ANSI_CPRNG"
disable_config "CRYPTO_USER_API_HASH"
disable_config "CRYPTO_USER_API_SKCIPHER"
disable_config "CRYPTO_USER_API_RNG"
disable_config "CRYPTO_USER_API_AEAD"
disable_config "CRYPTO_HASH_INFO"
disable_config "CRYPTO_HW"
disable_config "CRYPTO_DEV_QCOM_RNG"

echo "Removing unused I2C/SPI drivers..."

# Disable unused I2C/SPI drivers
disable_config "I2C_DEBUG_CORE"
disable_config "I2C_DEBUG_ALGO"
disable_config "I2C_DEBUG_BUS"
disable_config "SPI_DEBUG"

echo "Removing unused PHY drivers..."

# Disable unused PHY drivers
disable_config "AMD_PHY"
disable_config "AQUANTIA_PHY"
disable_config "AT803X_PHY"
disable_config "BCM7XXX_PHY"
disable_config "BCM87XX_PHY"
disable_config "BROADCOM_PHY"
disable_config "CICADA_PHY"
disable_config "CORTINA_PHY"
disable_config "DAVICOM_PHY"
disable_config "DP83848_PHY"
disable_config "DP83867_PHY"
disable_config "ICPLUS_PHY"
disable_config "INTEL_XWAY_PHY"
disable_config "LSI_ET1011C_PHY"
disable_config "LXT_PHY"
disable_config "MARVELL_PHY"
disable_config "MARVELL_10G_PHY"
disable_config "MICREL_PHY"
disable_config "MICROCHIP_PHY"
disable_config "MICROSEMI_PHY"
disable_config "NATIONAL_PHY"
disable_config "QSEMI_PHY"
disable_config "REALTEK_PHY"
disable_config "ROCKCHIP_PHY"
disable_config "SMSC_PHY"
disable_config "STE10XP"
disable_config "TERANETICS_PHY"
disable_config "VITESSE_PHY"
disable_config "XILINX_GMII2RGMII"

echo "Removing unused PPP features..."

# Disable unused PPP features
disable_config "PPP_MULTILINK"
disable_config "PPPOE"
disable_config "PPP_ASYNC"
disable_config "PPP_SYNC_TTY"
disable_config "SLIP"

echo "Removing unused WLAN features..."

# Disable unused WLAN features
disable_config "WLAN_VENDOR_ADMTEK"
disable_config "WLAN_VENDOR_ATH"
disable_config "WLAN_VENDOR_ATMEL"
disable_config "WLAN_VENDOR_BROADCOM"
disable_config "WLAN_VENDOR_CISCO"
disable_config "WLAN_VENDOR_INTEL"
disable_config "WLAN_VENDOR_INTERSIL"
disable_config "WLAN_VENDOR_MARVELL"
disable_config "WLAN_VENDOR_MEDIATEK"
disable_config "WLAN_VENDOR_RALINK"
disable_config "WLAN_VENDOR_REALTEK"
disable_config "WLAN_VENDOR_RSI"
disable_config "WLAN_VENDOR_ST"
disable_config "WLAN_VENDOR_TI"
disable_config "WLAN_VENDOR_ZYDAS"
disable_config "WLAN_VENDOR_QUANTENNA"
disable_config "USB_NET_RNDIS_WLAN"
disable_config "CNSS_QCA6290"
disable_config "CNSS_QCA6390"
disable_config "CNSS_EMULATION"
disable_config "CNSS_SUPPORT_DUAL_DEV"
disable_config "CNSS"
disable_config "CLD_DEBUG"
disable_config "CLD_USB_CORE"
disable_config "CLD_HL_SDIO_CORE"
disable_config "CNSS_LOGGER"
disable_config "WLAN_FEATURE_RX_WAKELOCK"

echo "Removing unused thermal features..."

# Disable unused thermal features
disable_config "THERMAL_WRITABLE_TRIPS"
disable_config "THERMAL_GOV_FAIR_SHARE"
disable_config "THERMAL_GOV_BANG_BANG"
disable_config "THERMAL_GOV_USER_SPACE"
disable_config "THERMAL_GOV_POWER_ALLOCATOR"
disable_config "THERMAL_EMULATION"

echo "Removing unused GPIO features..."

# Disable unused GPIO features
disable_config "GPIO_SYSFS"
disable_config "GPIO_GENERIC"

echo "Removing unused MISC drivers..."

# Disable unused misc drivers
disable_config "QPNP_MISC"

echo "Optimizing kernel configuration..."

# Enable some optimizations
disable_config "CC_OPTIMIZE_FOR_SIZE"  # This might actually increase size
disable_config "SLUB_DEBUG"
disable_config "SLAB_FREELIST_RANDOM"
disable_config "SLAB_FREELIST_HARDENED"

echo "Debloat completed!"
echo "Original defconfig backed up as: arch/arm64/configs/surya_defconfig.backup"
echo ""
echo "To test the new configuration:"
echo "  make ARCH=arm64 surya_defconfig"
echo "  make ARCH=arm64 menuconfig  # to review changes"
echo "  make ARCH=arm64 -j$(nproc)  # to build"